#!/bin/bash

# Name of the Python script
PYTHON_SCRIPT="src.server.run"

# # Check if the Python script exists
# if [[ ! -f "$PYTHON_SCRIPT" ]]; then
#     echo "Error: $PYTHON_SCRIPT not found!"
#     exit 1
# fi

# Run the Python script
python -m "$PYTHON_SCRIPT"

# Check if the Python script ran successfully
if [[ $? -eq 0 ]]; then
    echo "Python script executed successfully."
else
    echo "Python script failed to execute."
    exit 1
fi
